### ISSUE TITLE
Latest updates not released

### ISSUE THREAD

**Issue by maxjacobson** [AtomLinter/linter-codeclimate#46]
Hello @Arcanemagus, @mrb, or whom it may concern!

I work at Code Climate. I was just using this package on a markdown document and noticed that markdownlint issues weren't appearing.

I believe the reason is that this package hasn't been released since December 2015. Is that right? markdownlint support was added in April.

I'm not personally familiar with the process for releasing Atom packages, but would love to help in any way I can.

**Comment by Arcanemagus** [comment]
I'll push out a release, it doesn't _look_ like any of [the changes](https://github.com/AtomLinter/linter-codeclimate/compare/v0.1.2...00c4ded) here should cause problems.

**Comment by maxjacobson** [comment]
@Arcanemagus Thanks, that sounds great.

At first I thought it was a bug with the current implementation of engine-picking, but then noticed it hadn't been released. When I thought it was a bug, I wanted to add a spec, but couldn't figure out how to run the specs. Do you know how? I noticed this repo doesn't have a `.travis.yml` either. This question is kind of unrelated to the issue, but just curious :)

**Comment by Arcanemagus** [comment]
`apm test` in the CLI or "View -> Developer -> Run Package Specs" within Atom will run the specs, I apparently have a local branch from 9 months ago with some CI config... I'm not sure why they weren't released so I'm checking on that now.

**Comment by maxjacobson** [comment]
Ah, neat, I didn't know that was a thing. If it were in a CI config that would be sufficient for discoverability. Putting it in the README (for atom noobs like me 😄) would also be helpful but not necessary if it's not your style :)

**Comment by Arcanemagus** [comment]
v0.2.0 is published with the `reek` and `markdownlint` additions.

**Comment by maxjacobson** [comment]
Awesome, thanks.

I'm getting this error on save now after updating:

```

TypeError: Helpers.findFile is not a function
    at Object.provider.lint (/Users/maxjacobson/src/linter-codeclimate/lib/linter-codeclimate.coffee:75:41)
    at promises.push.Promise.then._this.emitter.emit.linter (/Users/maxjacobson/.atom/packages/linter/lib/linter-registry.js:63:26)
    at /Users/maxjacobson/.atom/packages/linter/lib/linter-registry.js:62:23
    at Set.forEach (native)
    at LinterRegistry.lint (/Users/maxjacobson/.atom/packages/linter/lib/linter-registry.js:60:18)
    at /Users/maxjacobson/.atom/packages/linter/lib/linter.coffee:98:16
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /Users/maxjacobson/.atom/packages/linter/lib/editor-linter.js:30:20
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1154:27)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1124:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:871:26)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:738:18)
    at Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:3:59)
    at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:721:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:693:35)
    at atom-workspace.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:222:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:587:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:382:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:59)
```

**Comment by maxjacobson** [comment]
Also, not necessarily related, but `apm test` currently fails

**Comment by Arcanemagus** [comment]
And that is why I hate projects that don't have CI builds 😞. (I'm on Windows so I can't test locally.)

**Comment by maxjacobson** [comment]
Heh, yea

I'm guessing the relevant change is the atom-linter upgrade. Want to try downgrading that back to how it was? I can open a PR for that if you'd like

**Comment by Arcanemagus** [comment]
I'll just fix it, it's a simple rename of the function 😉.

**Comment by Arcanemagus** [comment]
v0.2.1 pushed out which fixes the function reference.

**Comment by Arcanemagus** [comment]
I'm going to close this issue as things should be published and working now, anything else can be filed as a new issue.

**Comment by maxjacobson** [comment]
Can confirm things are looking good -- thanks for your availability to push this through 😄
